### ISSUE TITLE
Server Side Rendering without external binary

### ISSUE THREAD

**Issue by mrueg** [abhinav/goldmark-mermaid#28]
Currently goldmark-mermaid requires mmdc to be installed for server-side rendering. 

Would it be possible to support https://github.com/dreampuf/mermaid.go (or a solution similar to it), that allows to carry the necessary mermaid tooling within go?

**Comment by abhinav** [comment]
Hey, @mrueg, that's an interesting idea.

I wasn't aware of mermaid.go. Looking at the source, it relies on Chrome DevTools Protocol to do the heavy lifting.
Unless I'm missing something, that means a Chromium-based browser must be installed on the system for that to work, so it's not entirely independent. (Although, I think `mmdc` also relies on chromedp for rendering.)

Regardless, I agree that this would be an improvement over shelling out to `mmdc` on a per-diagram basis.
So yeah, I think it would make sense to add an opt-in for something like this.

**Comment by mrueg** [comment]
Yes, `mmdc` relies on chrome + puppeteer for rendering. This approach is using https://github.com/chromedp/chromedp
